language: node_js
node_js:
  - "10"
install: yarn
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      script: bash ./travis-deploy.sh
cache:
  yarn: true
  directories:
    - node_modules
